#define WIFI_SSID ""
#define WIFI_PASSWORD ""
#define MQTT_HOST ""
#define MQTT_PORT 1883
#define MQTT_TOPIC "homey"
#define HOMEY_DEVICE_ID "HDT-01"
#define HOMEY_LOCATION "Bathroom"
#define DEBUG 0
#define DELAY_SECONDS 60
